name: Deploy React App to GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Listar conteúdo do diretório
        run: |
          pwd
          ls -la
      
      - name: Verificar package.json
        run: cat package.json
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Instalar dependências
        run: |
          npm install
          npm list || true
      
      - name: Verificar script de build
        run: npm run build --verbose
        env:
          CI: false  # Trata warnings como não fatais
      
      - name: Listar conteúdo do diretório de build
        run: |
          ls -la build || true
          ls -la dist || true
      
      - name: Upload da build para GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./client/build
          retention-days: 1
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
